name: Python - Testing

on:
  workflow_dispatch:
  push:
    branches: [master, develop]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          lfs: true
          python-version: 3.9
      - name: Checkout LFS objects
        run: |
          git lfs pull
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip;
          python -m pip install -r requirements.txt;
      - name: Test with pytest
        run: |
          make tests_run
