name: Python - Testing

on:
  workflow_dispatch:
  push:
    branches: [master, develop]
  pull_request:

jobs:
  pytest:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt --user --force-reinstall --no-cache-dir
      - name: Show media files
        run: |
          ls -R /pictures
          ls -R /videos
      - name: Copy assets from remote storage
        run: |
          cp /pictures/* ./assets/pictures/
          cp /videos/* ./assets/videos/
      - name: Test with pytest
        run: |
          export PATH="/home/runner/.local/bin:$PATH"
          make tests_run
